[workspace]
members = [
    "crates/alloc",
    "crates/flipperzero",
    "crates/rt",
    "crates/sys",
]

[profile.dev]
opt-level = "z"
panic = "abort"

[profile.release]
opt-level = "z"
panic = "abort"
