[package]
name = "flipperzero"
version = "0.7.2"
description = "Rust for Flipper Zero"
repository = "https://github.com/dcoles/flipperzero-rs"
readme = "../../README.md"
license = "MIT"
edition = "2021"
rust-version = "1.64.0"
autobins = false
autotests = false
autobenches = false

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
targets = []
all-features = true

[lib]
bench = false
test = false

[dependencies]
flipperzero-sys = { path = "../sys", version = "0.7.2" }
ufmt = "0.2.0"

[dev-dependencies]
flipperzero-alloc = { path = "../alloc", version = "0.7.2" }
flipperzero-rt = { path = "../rt", version = "0.7.2" }

[features]
default = ["unstable_lints", "unstable_intrinsics"]
# enables all optional services
all-services = ["service-gui", "service-dialogs"]
# enables features requiring an allocator
alloc = []
# enables unstable Rust intrinsics
unstable_intrinsics = []
# enables unstable Rust lints on types provided by this crate
unstable_lints = []
# enables GUI APIs of Flipper
service-gui = ["alloc"]
# enables Dialogs APIs of Flipper
service-dialogs = ["service-gui"]

[[example]]
name = "dialog"
required-features = ["service-dialogs"]

[[example]]
name = "gui"
required-features = ["service-gui"]
