[package]
name = "flipperzero"
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
autobins = false
autotests = false
autobenches = false

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
targets = []
all-features = true

[lib]
bench = false
harness = false

[dependencies]
flipperzero-sys.workspace = true
flipperzero-test.workspace = true
ufmt.workspace = true

# HAL wrappers
rand_core = "0.6"

# Furi wrappers
lock_api = "0.4"

# Toolbox
digest = "0.10"
bitflags = "1.0"

[dev-dependencies]
flipperzero-alloc.workspace = true
flipperzero-rt.workspace = true

# Toolbox
crc32fast = { version = "1", default-features = false }
md-5 = { version = "0.10", default-features = false }
sha2 = { version = "0.10", default-features = false }

[features]
default = ["unstable_lints", "unstable_intrinsics"]
# enables all optional services
all-services = ["service-gui", "service-dialogs"]
# enables features requiring an allocator
alloc = []
# enables unstable Rust intrinsics
unstable_intrinsics = []
# enables unstable Rust lints on types provided by this crate
unstable_lints = []
# enables GUI APIs of Flipper
service-gui = ["alloc"]
# enables Dialogs APIs of Flipper
service-dialogs = ["service-gui"]

[[test]]
name = "dolphin"
harness = false

[[test]]
name = "string"
harness = false

[[example]]
name = "dialog"
required-features = ["service-dialogs"]

[[example]]
name = "gui"
required-features = ["service-gui"]

[[example]]
name = "threads"
required-features = ["alloc"]
