[package]
name = "flipperzero"
version = "0.6.0-alpha"
description = "Rust for Flipper Zero"
repository = "https://github.com/dcoles/flipperzero-rs"
readme = "../../README.md"
license = "MIT"
edition = "2021"
rust-version = "1.64.0"
autobins = false
autotests = false
autobenches = false

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
targets = []
all-features = true

[lib]
bench = false
test = false

[dependencies]
flipperzero-sys = { path = "../sys", version = "0.6.0-alpha" }

[dev-dependencies]
flipperzero-rt = { path = "../rt", version = "0.6.0-alpha" }

[features]
default = ["unstable_lints"]
# enables features requiring an allocator
alloc = []
# enables unstable Rust lints on types provided by this crate
unstable_lints = []
