[package]
name = "flipperzero-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.63.0"
bytes = "1.4.0"
camino = "1.1.2"
clap = { version = "4.0.32", features = ["cargo", "derive"] }
crossterm = "0.26.1"
csv = "1.1.6"
doxygen-rs = "0.3.1"
once_cell = "1.17.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serialport = "4.2.0"
shlex = "1.1.0"
