[package]
name = "flipperzero-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.63.0"
camino = "1.1.2"
clap = { version = "4.0.32", features = ["cargo"] }
csv = "1.1.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
shlex = "1.1.0"
